Add Cron Job and Job additional lab
appuio/techlab pull request #35
Opened 2018-12-04 10:52 UTC by phil-pona

Thanks to the kuberntes job and cronjob techlab from @bliemli I created an additional lab for this techlab

2018-12-04 19:57 UTC, bliemli requested changes

2018-12-04 19:57 UTC, bliemli commented on additional-labs/resources/cronjob_mysql-dump.yaml
> +              value: appuio
```suggestion
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: mysql
```

2018-12-04 19:57 UTC, bliemli commented on additional-labs/resources/cronjob_mysql-dump.yaml
> +              value: appuio
```suggestion
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mysql
```

2018-12-04 19:57 UTC, bliemli commented on additional-labs/resources/cronjob_mysql-dump.yaml
> +              value: appuio
```suggestion
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mysql
```

2018-12-04 19:57 UTC, bliemli commented on additional-labs/resources/job_mysql-dump.yaml
> +          value: appuio
```suggestion
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql
```

2018-12-04 19:57 UTC, bliemli commented on additional-labs/resources/job_mysql-dump.yaml
> +          value: appuio
```suggestion
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mysql
```

2018-12-04 19:57 UTC, bliemli commented on additional-labs/resources/job_mysql-dump.yaml
> +          value: appuio
```suggestion
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mysql
```

2018-12-05 07:46 UTC, bliemli approved these changes

2018-12-05 07:47 UTC, merged

2018-12-05 07:47 UTC, phil-pona commented
thanks

2018-12-05 07:47 UTC, bliemli commented
Thank you!