Configmap Extended Lab
appuio/techlab pull request #37
Opened 2018-12-05 09:14 UTC by phil-pona

This PR adds the extended lab on how to use configmaps, it's based on the kubernetes techlab

2018-12-06 19:38 UTC, bliemli requested changes

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +ConfigMaps erlauben ähnlich wie das setzen von Umgebungsvariablen die Konfiguration für eine Applikation vom Image zu trennen und bei Laufzeit dem Pod zur Verfügung zu stellen um Applikationen innerh
```suggestion
ConfigMaps werden dazu verwendet, die Konfiguration für eine Applikation vom Image zu trennen und bei Laufzeit dem Pod zur Verfügung zu stellen, ähnlich dem Setzen von Umgebungsvariablen. Dies erlaubt es, Applikationen innerhalb von Containern möglichst portabel zu halten.
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +In diesem Lab lernen Sie wie man ConfigMaps erstellt und entsprechend verwendet.
```suggestion
In diesem Lab lernen Sie, wie man ConfigMaps erstellt und entsprechend verwendet.
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +Mit dem folgenden Befehl legen wir nun die erste ConfigMap auf Basis eines localen Files an:
```suggestion
Mit dem folgenden Befehl legen wir nun die erste ConfigMap auf Basis eines lokalen Files an:
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +Als nächstest wollen wir die ConfigMap im Pod verfügbar machen.
```suggestion
Als nächstes wollen wir die ConfigMap im Pod verfügbar machen.
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +Grundsätzlich gibt es dafür die folgenden Möglichkeiten: https://docs.openshift.com/container-platform/3.11/dev_guide/configmaps.html#consuming-configmap-in-pods
```suggestion
Grundsätzlich gibt es dafür die folgenden Möglichkeiten, welche in der [offiziellen Dokumentation](https://docs.openshift.com/container-platform/3.9/dev_guide/configmaps.html#consuming-configmap-in-pods) genauer beschrieben werden:
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +dafür müssen wir entweder den Pod oder in unserem Fall das Deployment `oc edit dc example-spring-boot` bearbeiten.
```suggestion
Hierfür müssen wir entweder den Pod oder in unserem Fall das Deployment mit `oc edit dc example-spring-boot` bearbeiten.
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +Zu beachten gilt es den volumeMounts (`spec.template.spec.containers.volumeMounts`wie wird das Volume in den Container gemountet) und volumes (`spec.template.spec.volumes` welches Volume in unserem F
```suggestion
Zu beachten gilt es dabei den volumeMounts- (`spec.template.spec.containers.volumeMounts`: wie wird das Volume in den Container gemountet) sowie den volumes-Teil (`spec.template.spec.volumes`: welches Volume in unserem Fall die ConfigMap wird in den Container gemountet).
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +anschliessend kann im Container im file /etc/config/properties.properties auf die Werte zugegriffen werden.
```suggestion
Anschliessend kann im Container im File `/etc/config/properties.properties` auf die Werte zugegriffen werden.
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +Diese Property File kann nun so von der Java Applikation im Conainer gelesen und verwendet werden. Das Image bleibt dabei umgebungsneutral.
```suggestion
Diese Property File kann nun so von der Java Applikation im Container gelesen und verwendet werden. Das Image bleibt dabei umgebungsneutral.
```

2018-12-06 19:38 UTC, bliemli commented on additional-labs/configmaps.md
> +Erstellen Sie jeweils eine ConfigMap und verwenden Sie dafür die verschiedenen Arten von Data Sources https://docs.openshift.com/container-platform/3.11/dev_guide/configmaps.html#consuming-configmap-
```suggestion
Erstellen Sie jeweils eine ConfigMap und verwenden Sie dafür die verschiedenen Arten von [Data Sources](https://docs.openshift.com/container-platform/3.9/dev_guide/configmaps.html#consuming-configmap-in-pods).
```

2018-12-06 19:50 UTC, merged

2018-12-06 20:02 UTC, phil-pona commented
Thanks for the review and the fixes

2018-12-07 07:22 UTC, bliemli commented
Thank you for the PR!