Add secret description and integration into springboot application
appuio/techlab pull request #38
Opened 2018-12-06 14:11 UTC by phil-pona

Updates the Lab 8 and describes how Secrets can be used and integrated into both pods, mysql and springboot.

fixes #36

2018-12-06 19:53 UTC, bliemli requested changes

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +### Passwort und Username als plaintext?
```suggestion
### Passwort und Username als Plaintext?
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Beim Deployen der Datebank sowohl via CLI aber auch via Web Console, haben wir mittels Parameter oder direkt im Eingabefeld Werte für User, Passwort und Datenbank angegeben. In diesem Kapitel wollen
```suggestion
Beim Deployen der Datebank via CLI wie auch via Web Console haben wir mittels Parameter Werte für User, Passwort und Datenbank angegeben. In diesem Kapitel wollen wir uns nun anschauen, wo diese sensitiven Daten effektiv gelandet sind.
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Die Werte für die einzelnen Umgebungsvariablen kommen also aus einem sogenannten Secret, in unserem Fall hier aus dem Secret mit dem Namen `mysql`. In diesem Secret sind die vier Werte entsprechend u
```suggestion
Die Werte für die einzelnen Umgebungsvariablen kommen also aus einem sogenannten Secret, in unserem Fall hier aus dem Secret mit Namen `mysql`. In diesem Secret sind die vier Werte entsprechend unter den passenden Keys (`database-user`, `database-password`, `database-root-password`, `database-name`) abgelegt und können so referenziert werden.
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Schauen wir uns nun die neue Resource Secret mit dem Namen `mysql` an:
```suggestion
Schauen wir uns nun die neue Ressource Secret mit dem Namen `mysql` an:
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Die entsprechenden Key-Value Pairs sind unter Data ersichtlich:
```suggestion
Die entsprechenden Key-Value Pairs sind unter `data` ersichtlich:
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Die konkreten Werte sind mittels base64 enkodiert. Unter Linux oder in der Gitbash kann man sich den entsprechenden Wert einfach mittels:
```suggestion
Die konkreten Werte sind mittels base64 enkodiert. Unter Linux oder in der Gitbash kann man sich den entsprechenden Wert einfach mittels:
```
```suggestion
Die konkreten Werte sind base64-kodiert. Unter Linux oder in der Gitbash kann man sich den entsprechenden Wert einfach mittels:
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Mit Secrets können wir also sensitive Informationen(Credetials, Zertifikate, Schlüssel, dockercfg ...) abspeichern und entsprechend von den Pods entkoppeln. Gleichzeitig, haben wir damit die Möglichk
```suggestion
Mit Secrets können wir also sensitive Informationen (Credetials, Zertifikate, Schlüssel, dockercfg, ...) abspeichern und entsprechend von den Pods entkoppeln. Gleichzeitig haben wir damit die Möglichkeit, dieselben Secrets in mehreren Containern zu verwenden und so Redundanzen zu vermeiden.
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Secrets können entweder wie oben bei der mysql Datenbank in Umgebungsvaribablen gemappt oder direkt als Files via volumes in einen Container gemounted werden.
```suggestion
Secrets können entweder, wie oben bei der MySQL-Datenbank, in Umgebungsvariablen gemappt oder direkt als Files via Volumes in einen Container gemountet werden.
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Weitere Informationen zu Secrets können hier gefunden werden: https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html
```suggestion
Weitere Informationen zu Secrets können in der [offiziellen Dokumentation](https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html) gefunden werden.
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +## Aufgabe: LAB8.2.1: Setzen der Werte für Usernamen und Passwort aus dem Secret mysql
```suggestion
## Aufgabe: LAB8.2.1: Secret referenzieren
```

2018-12-06 19:53 UTC, bliemli commented on labs/08_database.md
> +Weiter oben haben wir gesehen, wie OpenShift mittels Secrets senisitive Informationen von der eigentlichen Konfiguration enkoppelt und uns dabei hilft Redundanzen zu vermeiden. Unsere Springboot Appl
```suggestion
Weiter oben haben wir gesehen, wie OpenShift mittels Secrets sensitive Informationen von der eigentlichen Konfiguration enkoppelt und uns dabei hilft, Redundanzen zu vermeiden. Unsere Springboot Applikation aus dem vorherigen Lab haben wir zwar korrekt konfiguriert, allerings aber die Werte redundant und Plaintext in der DeploymentConfig abgelegt.
```

2018-12-06 20:02 UTC, merged

2018-12-06 20:02 UTC, phil-pona commented
Thanks for the review and the fixes

2018-12-07 07:23 UTC, bliemli commented
Thank you for the PR!