Update 08_database.md
appuio/techlab pull request #49
Opened 2019-10-29 09:38 UTC by ombre8

Added Information about multiline delemiter on Windows
this fixes #44

2019-11-04 07:23 UTC, bliemli requested changes

2019-11-04 07:23 UTC, bliemli commented on labs/08_database.md
> +Über das CLI kann der MySQL Service wie folgt angelegt werden (Multiline command delimeter for cmd is the caret: `^`, for Powershell it is the backtick: `` ` ``.):
```suggestion
Über das CLI kann der MySQL Service wie folgt angelegt werden.

**Note**: Die Backslashes (`\`) dienen dazu, den langen Befehl übersichtlicher auf mehreren Zeilen abzubilden. **Auf Windows** ist der sog. Multiline Delimiter aber nicht der Backslash, sondern in cmd das Caret (`^`) und in PowerShell der Backtick (`` ` ``).```

2019-11-04 13:00 UTC, ombre8 commented on labs/08_database.md
> +Über das CLI kann der MySQL Service wie folgt angelegt werden (Multiline command delimeter for cmd is the caret: `^`, for Powershell it is the backtick: `` ` ``.):
```suggestion
Über das CLI kann der MySQL Service wie folgt angelegt werden.
**Note**: Die Backslashes (`\`) dienen dazu, den langen Befehl übersichtlicher auf mehreren Zeilen abzubilden. **Auf Windows** ist der sog. Multiline Delimiter aber nicht der Backslash, sondern in cmd das Caret (`^`) und in PowerShell der Backtick (`` ` ``).
```
gegenvorschlag ohne die `` ``` `` am schluss ;)

2019-11-04 13:01 UTC, bliemli commented on labs/08_database.md
> +Über das CLI kann der MySQL Service wie folgt angelegt werden (Multiline command delimeter for cmd is the caret: `^`, for Powershell it is the backtick: `` ` ``.):
Macht Sinn :+1:

2019-11-04 13:03 UTC, bliemli requested changes

2019-11-04 13:03 UTC, bliemli commented on labs/08_database.md
> +Befehl für das Setzen der Umgebungsvariablen (Multiline command delimeter for cmd is the caret: `^`, for Powershell it is the backtick: `` ` ``.):
```suggestion
Über das CLI kann der MySQL Service wie folgt angelegt werden.

**Note**: Die Backslashes (`\`) dienen dazu, den langen Befehl übersichtlicher auf mehreren Zeilen abzubilden. **Auf Windows** ist der sog. Multiline Delimiter aber nicht der Backslash, sondern in cmd das Caret (`^`) und in PowerShell der Backtick (`` ` ``).
```

2019-11-06 08:25 UTC, bliemli commented
Merci!

2019-11-06 08:25 UTC, merged