Workshop 3.11
appuio/techlab pull request #50
Opened 2020-01-07 15:27 UTC by chrira

Adding workshop labs for two-day developer training.

Updated and referenced existing labs.

2020-01-08 15:53 UTC, bliemli requested changes

2020-01-08 15:53 UTC, bliemli commented on labs/05_create_route.md
> +Die Applikation ist nun vom Internet her über den angegebenen Hostnamen erreichbar, Sie können also nun auf die Applikation zugreifen.
Den deutschen Kasus auf englische Wörter anzuwenden ist nicht sehr schön.

```suggestion
Die Applikation ist nun vom Internet her über den angegebenen Hostname erreichbar, Sie können also nun auf die Applikation zugreifen.
```

2020-01-08 15:53 UTC, bliemli commented on labs/05_create_route.md
> +In der Overview der Web Console ist diese Route mit dem Hostnamen jetzt auch sichtbar.
```suggestion
In der Overview der Web Console ist diese Route mit dem Hostname jetzt auch sichtbar.
```

2020-01-08 15:53 UTC, bliemli commented on labs/06_scale.md
> +Wenn wir unsere Beispiel-Applikation skalieren wollen, müssen wir unserem ReplicationController (rc) mitteilen, dass wir bspw. stets 3 Replicas des Images am Laufen haben wollen.
```suggestion
Wenn wir unsere Beispiel-Applikation skalieren wollen, müssen wir unserem ReplicationController (rc) mitteilen, dass wir bspw. stets 3 Replicas des Image am Laufen haben wollen.
```

2020-01-08 15:53 UTC, bliemli commented on labs/06_scale.md
> +weshalb wir diese skalieren müssen, damit die gewünschte Anzahl Repclias vom rc übernommen wird:
Wieso ein Zeilenumbruch nach dem Komma?

2020-01-08 15:53 UTC, bliemli commented on labs/06_scale.md
> +while true; do sleep 1; ( { curl --insecure -fs http://[HOSTNAME]/health/; date "+ TIME: %H:%M:%S,%3N" ;} & ) 2>/dev/null; done
Dann müsste die URL auf https geändert werden, ansonsten macht der --insecure-Parameter keinen Sinn.

2020-01-08 15:53 UTC, bliemli commented on labs/06_scale.md
> +* Readiness Probe: Gibt Feedback darüber, ob eine Applikation bereit ist, Requests zu empfangen. Ist v.a. im Rolling Update relevant.
Kann man so nicht sagen, ist in sehr vielen Fällen relevant.

```suggestion
* Readiness Probe: Gibt Feedback darüber, ob eine Applikation bereit ist, Requests zu empfangen
```

2020-01-08 15:53 UTC, bliemli commented on labs/06_scale.md
> +indem Sie die bereits verwendete While-Schlaufe während des folgenden Update-Befehls beobachten:
Wieso Zeilenumbruch nach Komma?

2020-01-08 15:53 UTC, bliemli commented on labs/06_scale.md
> +In der Web Console ist gut zu Beobachten, wie der Pod zuerst hellblau ist, bis die Applikation auf der Readiness Probe mit 0K antwortet.
```suggestion
In der Web Console ist gut zu beobachten, wie der Pod zuerst hellblau ist, bis die Readiness Probe meldet, dass die Applikation nun bereit ist.
```

2020-01-08 15:53 UTC, bliemli commented on labs/08_database.md
> +Einfacher ist es den Pod über die DeploymentConfiguration zu Referenzieren.
```suggestion
Einfacher ist es den Pod über die DeploymentConfig zu referenzieren.
```

2020-01-09 07:53 UTC, chrira commented on labs/06_scale.md
> +weshalb wir diese skalieren müssen, damit die gewünschte Anzahl Repclias vom rc übernommen wird:
ist reverted

2020-01-09 07:53 UTC, chrira commented on labs/06_scale.md
> +while true; do sleep 1; ( { curl --insecure -fs http://[HOSTNAME]/health/; date "+ TIME: %H:%M:%S,%3N" ;} & ) 2>/dev/null; done
ist reverted

2020-01-09 07:54 UTC, chrira commented on labs/06_scale.md
> +indem Sie die bereits verwendete While-Schlaufe während des folgenden Update-Befehls beobachten:
ist reverted

2020-01-10 09:54 UTC, bliemli requested changes

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Damit erhalten Sie Hilfe zur Projekt Ersellung
```suggestion
Damit erhalten Sie Hilfe zur Projekt Erstellung
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Openshift kann mehrere Benutzer (auch mit unterschiedlichen Rollen) in einem Projekt haben. Dazu können wir dem Projekt einzelne Benutzer hinzufügen oder einem Projekt auch eine Gruppe von Benutzern
```suggestion
OpenShift kann mehrere Benutzer (auch mit unterschiedlichen Rollen) in einem Projekt haben. Dazu können wir dem Projekt einzelne Benutzer oder auch eine Gruppe von Benutzern hinzufügen.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Weitere Informationen zu Rollen finden Sie [hier](https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/authorization.html#roles) und zu deren Verwaltung: [manage rbac](
```suggestion
Weitere Informationen zu Rollen finden Sie [hier](https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/authorization.html#roles) und zu deren Verwaltung [hier](https://docs.openshift.com/container-platform/3.11/admin_guide/manage_rbac.html).
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Um alle aktiven Rollen in Ihrem aktuellen Projekt anzuzeigen, können Sie Folgendes eingeben:
```suggestion
Um alle aktiven Rollen in Ihrem aktuellen Projekt anzuzeigen, können Sie folgendes eingeben:
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Alles in Openshift (Kubernetes) wird als Ressource repräsentiert, die wir anzeigen und abhängig von unseren Berechtigungen bearbeiten können.
```suggestion
Alles in OpenShift (Kubernetes) wird als Ressource repräsentiert, die wir anzeigen und abhängig von unseren Berechtigungen bearbeiten können.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Sie können alle Ressourcen Ihres aktuellen Projekts abrufen, indem Sie Folgendes eingeben:
```suggestion
Sie können alle Ressourcen Ihres aktuellen Projekts abrufen, indem Sie folgendes eingeben:
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +    oc get all --all-namespaces
Funktioniert nur als cluster-admin.

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Nehmen Sie das Projekt openshift-web-console, das einige Ressourcen zum Untersuchen enthält.
```suggestion
Nehmen Sie das Projekt openshift-web-console, das einige Ressourcen zum untersuchen enthält.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Sie sind nicht glücklich darüber, wie Ihre aktuellen Projekte verlaufen sind, und möchten von vorne beginnen?
```suggestion
Sie sind nicht glücklich darüber, wie Ihre aktuellen Projekte verlaufen sind und möchten von vorne beginnen?
```

2020-01-10 09:54 UTC, bliemli commented on workshop/01_using_oc_cli.md
> +Sie können sich jederzeit einen Überblick über Ihre aktuellen Ressourcen verschaffen, indem Sie Folgendes eingeben:
```suggestion
Sie können sich jederzeit einen Überblick über Ihre aktuellen Ressourcen verschaffen, indem Sie folgendes eingeben:
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +Bereiten Sie einen temporären Ordner vor und erstellen Sie die darin die Deployment Ordnerstruktur.
```suggestion
Bereiten Sie einen temporären Ordner vor und erstellen Sie darin die Deployment Verzeichnisstruktur.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +### Erstellen Sie die Deployment Ordnerstruktur
```suggestion
### Erstellen Sie die Deployment Verzeichnisstruktur
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +### Erstellen Sie einen neuen Build mit dem Wildfly Docker Image
```suggestion
### Erstellen Sie einen neuen Build mit dem Wildfly Container Image
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +* basis Docker Image: `openshift/wildfly-160-centos7`
```suggestion
* Basis Container Image: `openshift/wildfly-160-centos7`
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +Das Flag *binary=true* zeigt an, dass dieser Build seine Daten als Input erhält anstatt dass er ihn über eine URL (Git Repo) holt.
```suggestion
Das Flag *binary=true* zeigt an, dass dieser Build seine Daten direkt als Input erhält, anstatt via URL (Git Repo).
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +## Build Starten
```suggestion
## Build starten
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +### Eine neue Applikation Erstellen
```suggestion
### Eine neue Applikation erstellen
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +Starten Sie den Build mit den Daten aus `workshop/data/02_httpd`:
`workshop` nebst `labs` als Verzeichnisnamen halte ich für etwas unglücklich gewählt. `devlabs` o.ä. wäre evtl. besser geeignet, es geht ja ums Dev Techlab?

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +Verfolgen Sie, wie der Build abläuft und ob das Image in Ihrer Registrierung vorhanden sein wird.
```suggestion
Verfolgen Sie, wie der Build abläuft und ob das Image in Ihrer Registry vorhanden sein wird.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/02_builds.md
> +    Fügen Sie im Dockerfile einen COPY-befehl hinzu, um die Datei easter-egg.txt nach /var/www/html/ zu kopieren :<br/>
```suggestion
    Fügen Sie im Dockerfile einen COPY-Befehl hinzu, um die Datei easter-egg.txt nach /var/www/html/ zu kopieren :<br/>
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +# Applikation Entwickeln
```suggestion
# Applikation entwickeln
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +In diesen Labs werden wir Applikationen Entwickeln.
```suggestion
In diesen Labs werden wir Applikationen entwickeln.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +Ziel ist es eine Java Spring Boot Applikation lokal zu Bauen und mittels Binary Build auf die Plattform zu bringen.
```suggestion
Ziel ist es eine Java Spring Boot Applikation lokal zu bauen und mittels Binary Build auf die Plattform zu bringen.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +* Siehe dazu das Binary Build Beispiel des Labs [workshop/02_builds.md](./02_builds.md) an.
```suggestion
* Siehe dazu das Binary Build Beispiel des Labs [workshop/02_builds.md](./02_builds.md).
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +### Applikation Bauen
```suggestion
### Applikation bauen
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +<details><summary>Git Klone Befehl</summary>git clone https://github.com/appuio/example-spring-boot-helloworld.git</details><br/>
```suggestion
<details><summary>Git Clone Befehl</summary>git clone https://github.com/appuio/example-spring-boot-helloworld.git</details><br/>
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +### Deployment Ordner Struktur
```suggestion
### Deployment Verzeichnisstruktur
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +    <summary>Applikation Bauen</summary>
```suggestion
    <summary>Applikation bauen</summary>
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +Für den Binary Build eine Ordner Struktur vorbreiten mit dem Jar vom Java Build.
```suggestion
Für den Binary Build eine Verzeichnisstruktur vorbereiten mit dem Jar vom Java Build.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/03_develop.md
> +### Applikation Testen
```suggestion
### Applikation testen
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +## Aufgabe 2: Readyness check
```suggestion
## Aufgabe 2: Readyness Check
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +In einer früheren Aufgabe haben wir für die Rolling update Strategie einen Readyness check auf einen /health eingerichtet.
```suggestion
In einer früheren Aufgabe haben wir für die Rolling Update-Strategie einen Readyness Check auf dem Pfad /health eingerichtet.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Dieser Endpoint war über die Route nicht erreichbar. Wie kann der endpoint nun erreicht werden?
```suggestion
Dieser Endpoint war über die Route nicht erreichbar. Wie kann der Endpoint nun erreicht werden?
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +In diesem Beispiel werden wir eine Applikation automatisierte hoch und runter skalieren, je nach dem unter wieviel Last die Applikation steht. Dazu verwenden wir eine Ruby example webapp.
```suggestion
In diesem Beispiel werden wir eine Applikation automatisiert hoch- und runterskalieren, je nachdem unter wieviel Last die Applikation steht. Dazu verwenden wir eine Ruby Example Webapp.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Warten sie bis die Applikation gebaut und ready ist und erste Metriken auftauchen. Sie können dem Build, wie auch den vorhandenden Pods folgen.
```suggestion
Warten sie bis die Applikation gebaut und ready ist und erste Metriken auftauchen. Sie können dem Build wie auch den vorhandenden Pods folgen.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Nun definieren wir ein Set an Limiten für unsere Applikation, die für einen einzelnen Pod gültigkeit haben.
```suggestion
Nun definieren wir ein Set an Limiten für unsere Applikation, die für einen einzelnen Pod Gültigkeit hat.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Dazu editieren wir die `ruby-ex` DeploymentConfiguration:
```suggestion
Dazu editieren wir die `ruby-ex` DeploymentConfig:
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Folgende Resource Limiten fügen wir dem Container hinzu:
```suggestion
Folgende Resource Limits fügen wir dem Container hinzu:
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Sobald unser neuer Container läuft können wir nun den autoscaler konfigurieren:
```suggestion
Sobald unser neuer Container läuft können wir nun den Autoscaler konfigurieren:
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Folgendermassen können wir unseren pods folgen:
```suggestion
Folgendermassen können wir Statusänderungen unserer Pods folgen:
```

2020-01-10 09:54 UTC, bliemli commented on workshop/04_debugging_logs_metrics.md
> +Sobald wir die Last beenden wird die Anzahl Pods nach einer gewissen Zeit automatisch wieder herunter skaliert. Die Kapazität wird jedoch eine Weile vorenthalten.
Was willst du mit 

> Die Kapazität wird jedoch eine Weile vorenthalten.

sagen?

```suggestion
Sobald wir die Last beenden wird die Anzahl Pods nach einer gewissen Zeit automatisch wieder verkleinert. Die Kapazität wird jedoch eine Weile vorenthalten.
```

2020-01-10 09:54 UTC, bliemli commented on workshop/README.md
> +# Workshop - HandsOn
Hier auch das Thema betr. Benennung.

2020-01-10 09:54 UTC, bliemli commented on workshop/README.md
> +* [auf OpenShift Builden](02_builds.md)
```suggestion
* [Builds](02_builds.md)
```

2020-01-10 09:54 UTC, bliemli commented on workshop/README.md
> +* [Applikationen Entwickeln](03_develop.md)
```suggestion
* [Applikationen entwickeln](03_develop.md)
```

2020-01-10 11:05 UTC, chrira commented on workshop/02_builds.md
> +Starten Sie den Build mit den Daten aus `workshop/data/02_httpd`:
Es sind die Labs, welche ich an der 2-tägigen Schulung als Hands-On verwende.

2020-01-10 11:56 UTC, bliemli commented on workshop/02_builds.md
> +Starten Sie den Build mit den Daten aus `workshop/data/02_httpd`:
Das ist das DEV Techlab. Analog Verzeichnis `additional-labs` würde sich `dev-labs` als Verzeichnisnamen anstelle von `workshop` anbieten, ansonsten sehe ich hier Verwechslungsgefahr.

2020-01-10 13:04 UTC, chrira commented on workshop/02_builds.md
> +Starten Sie den Build mit den Daten aus `workshop/data/02_httpd`:
Merci, habe alles nach dev-labs umbenannt.

2020-01-10 13:04 UTC, chrira commented on workshop/README.md
> +# Workshop - HandsOn
Merci, habe alles nach dev-labs umbenannt.

2020-01-10 13:08 UTC, bliemli requested changes

2020-01-10 13:08 UTC, bliemli commented on README.md
> +Unterlagen für eine 2-tägiges Developer Techlab sind im Ordner [dev-labs](dev-labs/) abgelegt.
```suggestion
Unterlagen für ein zweitägiges Developer Techlab sind im Verzeichnis [dev-labs](dev-labs/) abgelegt.
```

2020-01-10 13:08 UTC, bliemli commented on dev-labs/01_using_oc_cli.md
> +Sie können auch alle Ressourcen der Namespaces (Projekte) abrufen, auf die Sie Zugriff haben.
Löschen? Das war vorher ja das `--all-namespaces`-Beispiel, ohne diesen Parameter geht das aber nicht so einfach.

2020-01-10 13:17 UTC, chrira commented on dev-labs/01_using_oc_cli.md
> +Sie können auch alle Ressourcen der Namespaces (Projekte) abrufen, auf die Sie Zugriff haben.
Das ist bereits die Beschreibung für den folgenden Befehl:
oc get all -n openshift-web-console

2020-01-10 13:20 UTC, merged