Jenkins Pipelines Lab
appuio/techlab pull request #70
Opened 2020-12-09 14:12 UTC by chrira

Re-add Jenkins based pipelines lab for OCP 4

2021-02-11 12:27 UTC, bliemli requested changes

2021-02-11 12:27 UTC, bliemli commented on labs/13_template_creation.md
> +```
`oc types` doesn't seem to exist in my `oc` 4.6.9 client.

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Mit Jenkins Pipelines auf OpenShift hat man die Möglichkeit, komplexe CI/CD Prozesse voll integriert abzubilden. In diesem Lab zeigen wir, wie man mit Jenkins Pipelines arbeitet und so Applikationen
```suggestion
Mit Jenkins Pipelines auf OpenShift hat man die Möglichkeit, komplexe CI/CD Prozesse voll integriert abzubilden. In diesem Lab zeigen wir, wie man mit Jenkins Pipelines arbeitet und so Applikationen baut, testet und entsprechend kontrolliert in die verschiedenen Stages deployt.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Diese, Tekton basierten, Pipelines sind jedoch erst als Technology Preview Feature verfügbar [OpenShift 4 Pipeline Builds](https://docs.openshift.com/container-platform/latest/pipelines/understanding
```suggestion
Diese Tekton-basierten Pipelines sind jedoch erst als Technology Preview Feature verfügbar [OpenShift 4 Pipeline Builds](https://docs.openshift.com/container-platform/latest/pipelines/understanding-openshift-pipelines.html).
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Jetzt deployen wir Jenkins in user Projekt:
```suggestion
Jetzt deployen wir Jenkins in unser Projekt:
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Akzeptieren Sie diese und wechseln Sie zum nächsten Bildschirm, indem Sie auf 'Alow selected permissions' klicken.
```suggestion
Akzeptieren Sie diese und wechseln Sie zum nächsten Bildschirm, indem Sie auf 'Allow selected permissions' klicken.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Die Pipeline aus der BuildConfig ist im Ordner vom unserem OpenShift Projekt sichtbar.
```suggestion
Die Pipeline aus der BuildConfig ist im Ordner unseres OpenShift Projekts sichtbar.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Die Testpipeline besteht aus sechs Pipeline-Stages, welche auf zwei Jenkins Slaves ausgeführt werden. Die `Build` Pipeline-Stage, ist aktuell die einzig ausprogrammierte Stage. Sie startet nämlich im
```suggestion
Die Testpipeline besteht aus sechs Pipeline-Stages, welche auf zwei Jenkins Slaves ausgeführt werden. Die `Build` Pipeline-Stage ist aktuell die einzig ausprogrammierte Stage. Sie startet nämlich im aktuellen OpenShift Projekt den Image Build für unsere Applikation und wartet entsprechend bis dieser erfolgreich abgeschlossen ist.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Wir legen mit folgendem Befehl die entsprechende BuildConfig an, welche das JenkinsFile, also die Pipeline, direkt beinhaltet. Ebenso wird eine zweite BuildConfig erstellt. Diese enthält die Docker B
```suggestion
Wir legen mit folgendem Befehl die entsprechende BuildConfig an, welche das JenkinsFile, also die Pipeline, direkt beinhaltet. Ebenso wird eine zweite BuildConfig erstellt. Diese enthält die BuildConfig für die eigentliche Applikation, die wir im Rahmen dieser Pipeline deployen wollen. Im vorliegenden Beispiel eine simple PHP Applikation:
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +- Ein Build Projekt, CI/CD Umgebung Jenkins, Docker Builds, S2I Builds, ...
```suggestion
- Ein Build Projekt, CI/CD Umgebung Jenkins, Image Builds, S2I Builds, ...
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Im vorherigen Lab haben wir in der BuildConfig vom Typ `jenkinsPipelineStrategy` das JenkinsFile direkt angegeben. Als Alternative dazu kann das Jenkins Pipeline File auch via GitRepository in der Bu
```suggestion
Im vorherigen Lab haben wir in der BuildConfig vom Typ `jenkinsPipelineStrategy` das JenkinsFile direkt angegeben. Als Alternative dazu kann das Jenkins Pipeline File auch via Git Repository in der BuildConfig hinterlegt werden.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Mit dem OpenShift Jenkins Client Plugin kann so auf einfache Art direkt mit dem OpenShift Cluster kommuniziert werden und als Jenkinsfile komplexe CI/CD Pipelines implementieren:
```suggestion
Mit dem OpenShift Jenkins Client Plugin kann so auf einfache Art direkt mit dem OpenShift Cluster kommuniziert und als Jenkinsfile komplexe CI/CD Pipelines implementiert werden:
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Anschliessend definieren wir mittels dem label `role` noch, dass es sich um einen Jenkins Slave handelt:
```suggestion
Anschliessend definieren wir mittels dem Label `role` noch, dass es sich um einen Jenkins Slave handelt:
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Der einfachste Weg ist die Pipeline im Jenkins GUI zu Erweitern.
```suggestion
Der einfachste Weg ist die Pipeline im Jenkins GUI zu erweitern.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Über diesen Mechanismus lassen sich beliebige - auch selbst gebuildete - Jenkins Slaves aufsetzen und verwenden. Es stehen out-of-the-box ein `maven und gradle` sowie ein `NodeJS` Slave zur Verfügung
```suggestion
Über diesen Mechanismus lassen sich beliebige - auch selbst gebaute - Jenkins Slaves aufsetzen und verwenden. Es stehen out-of-the-box ein `maven` und `gradle` sowie ein `NodeJS` Slave zur Verfügung.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Will man selber Jenkins Slaves builden, sollte man auf dem `openshift/jenkins-slave-base-centos7` Image basieren.
```suggestion
Will man selber Jenkins Slaves bauen, sollte man auf dem `openshift/jenkins-slave-base-centos7` Image basieren.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Will man selber Jenkins Slaves builden, sollte man auf dem `openshift/jenkins-slave-base-centos7` Image basieren.
Ist centos7 wirklich noch ratsam?

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +- Pro Stage (dev, test, ..., prod) ein Projekt, welches die laufenden Pods und Services enthält, was uns erlaubt, sämtliche Umgebungen möglichst identisch zu halten
```suggestion
- Pro Stage (dev, test, ..., prod) ein Projekt, welches die laufenden Pods und Services enthält, was uns erlaubt, sämtliche Umgebungen praktisch identisch zu halten
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Nun müssen wir den `puller` Serviceaccount aus den entsprechenden Projekten pro Stage die nötigen Rechte geben, damit die gebuildeten Images gepullt werden können.
```suggestion
Nun müssen wir dem `puller` Serviceaccount aus den entsprechenden Projekten pro Stage die nötigen Rechte geben, damit die gebuildeten Images gepullt werden können.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Erstellen der Applikationen.
```suggestion
### Erstellen der Applikationen
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +In jeder Stage erstellen wir die Applikation anhand des vorher angelegten ImageStreams.
```suggestion
In jeder Stage erstellen wir nun die Applikation anhand des vorher angelegten ImageStreams.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Danach können wir noch die Applikation exposen.
```suggestion
Danach können wir noch die Applikation exponieren.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +In der Pipeline können wir nun mittels Setzen eines bestimmten Tags auf dem Imagestream der gebuildeten Applikation bspw. `application:dev`, das entsprechende Image in die passende Stage promoten und
```suggestion
In der Pipeline können wir nun mittels Setzen eines bestimmten Tags auf dem Imagestream der gebauten Applikation, bspw. `application:dev`, das entsprechende Image in die passende Stage promoten und deployen.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Führen Sie die Pipeline erneut aus und schauen Sie sich an, wie nun die gebuildete Applikation von Stage zu Stage deployt wird.
```suggestion
Führen Sie die Pipeline erneut aus und schauen Sie sich an, wie nun die gebaute Applikation von Stage zu Stage deployt wird.
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +## Deployment von Resourcen und Konfiguration
```suggestion
## Deployment von Ressourcen und Konfiguration
```

2021-02-11 12:27 UTC, bliemli commented on additional-labs/jenkins.md
> +Bisher haben wir nur die Applikation mittels unserer Deployment Pipeline deployt. Wie können wir nun unsere Pipeline auch dazu verwenden, um Resourcen (Deployments, Routen, Cronjobs...) zu deployen?
```suggestion
Bisher haben wir nur die Applikation mittels unserer Deployment Pipeline deployt. Wie können wir nun unsere Pipeline auch dazu verwenden, um Ressourcen (Deployments, Routen, Cronjobs...) zu deployen?
```

2021-02-24 10:55 UTC, chrira commented on labs/13_template_creation.md
> +```
thanks for the hint

2021-02-25 09:02 UTC, bliemli approved these changes

2021-02-25 12:40 UTC, merged